### ISSUE TITLE
Cannot install kio

### ISSUE THREAD

**Issue by mephi42** [KDE-mac/homebrew-kde#222]
The command is: `brew install kde-mac/kde/kf5-kio`

The error is:

```
file_unix.cpp:421:19: error: no matching function for call to 'getxattr'
    auto length = getxattr(filenameEncoded.data(), attrName, nullptr, 0);
                  ^~~~~~~~
/usr/include/sys/xattr.h:61:9: note: candidate function not viable: requires 6 arguments, but 4 were provided
ssize_t getxattr(const char *path, const char *name, void *value, size_t size, u_int32_t position, int options);
        ^
file_unix.cpp:427:14: error: no matching function for call to 'getxattr'
    length = getxattr(filenameEncoded.data(), attrName, strAttr, xattr_size);
             ^~~~~~~~
```

**Comment by mephi42** [comment]
Apparently caused by upstream commits https://github.com/KDE/kio/commit/d7cce9937d5e9af2753fadb82d11f308b58bb8fa and https://github.com/KDE/kio/commit/f1ab805c4ebcea24f0b84b785bc56515060e5eb2

**Comment by mephi42** [comment]
Reverting 59567193f38a8cdfb18b67523922fc3eb7f8b515 in /usr/local/Homebrew/Library/Taps/kde-mac/homebrew-kde helped.

**Comment by yurikoles** [comment]
@mephi42 please report it upstream.

**Comment by yurikoles** [comment]
Fixed in #223

**Comment by yurikoles** [comment]
Upstream issue: https://bugs.kde.org/show_bug.cgi?id=393304
